#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb 21 10:48:34 2019

@author: guochenxin
"""

#subnormal:
def detectSubnormalNumber(x):
    if 2**(-52-1022)<=abs(x)<=2**(-1022):
        return True
    else:
        return False


